# Generated by Django 5.2.8 on 2026-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_colaborador_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Teléfono"
            ),
        ),
    ]
