# Generated by Django 5.1.7 on 2025-09-25 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hackudc', '0005_token'), ('hackudc', '0006_alter_token_uuid'), ('hackudc', '0007_persona_verificado')]

    dependencies = [
        ('hackudc', '0004_alter_persona_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=None, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackudc.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
