# Generated by Django 5.1.7 on 2025-09-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackudc', '0005_token_squashed_0007_persona_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
